AWSTemplateFormatVersion: '2010-09-09'
Description: 'CheckResumeAI Infrastructure - Elastic Beanstalk, S3, and RDS on Free Tier'

Parameters:
  ApplicationName:
    Type: String
    Default: CheckResumeAI
    Description: Name of the Elastic Beanstalk application
    
  EnvironmentName:
    Type: String
    Default: CheckResumeAI-env
    Description: Name of the Elastic Beanstalk environment
    
  DBName:
    Type: String
    Default: checkresumeaidb
    Description: Database name
    
  DBUser:
    Type: String
    Default: checkresumeai
    Description: Database admin username
    
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database admin password
    
  S3BucketName:
    Type: String
    Default: checkresumeai-storage
    Description: S3 bucket for storing resumes and reports

Resources:
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - '*'
          AllowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - HEAD
          AllowedOrigins:
            - '*'
          ExposedHeaders:
            - ETag
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  
  # S3 Bucket Policy for Public Access to Reports
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForReportsAndPublicFiles
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/public/*']]

  # RDS Database Instance (PostgreSQL)
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join ['-', [!Ref ApplicationName, 'db']]
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: '14.4'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      BackupRetentionPeriod: 7
      PubliclyAccessible: true
      StorageType: gp2
      Tags:
        - Key: Application
          Value: !Ref ApplicationName

  # Elastic Beanstalk Application
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: AI-Powered Resume Analyzer SaaS

  # Elastic Beanstalk Environment
  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Ref EnvironmentName
      ApplicationName: !Ref ApplicationName
      SolutionStackName: '64bit Amazon Linux 2 v5.8.1 running Node.js 18'
      OptionSettings:
        # Environment Type
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
          
        # Environment Variables
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_ENV
          Value: production
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: S3_BUCKET
          Value: !Ref S3BucketName
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_HOSTNAME
          Value: !GetAtt RDSInstance.Endpoint.Address
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_PORT
          Value: !GetAtt RDSInstance.Endpoint.Port
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_DB_NAME
          Value: !Ref DBName
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_USERNAME
          Value: !Ref DBUser
          
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_PASSWORD
          Value: !Ref DBPassword
          
        # Instance Type
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
          
        # Node.js Version
        - Namespace: aws:elasticbeanstalk:container:nodejs
          OptionName: NodeVersion
          Value: '18.18.0'

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    
  S3BucketDomainName:
    Description: Domain name of the S3 bucket
    Value: !GetAtt S3Bucket.DomainName
    
  RDSEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Address
    
  RDSPort:
    Description: Port of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Port
    
  ElasticBeanstalkURL:
    Description: URL of the Elastic Beanstalk environment
    Value: !GetAtt ElasticBeanstalkEnvironment.EndpointURL
