branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: CheckResumeAI
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application

S3_BUCKET: checkresumeai-storage-2032721591
