[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "5000"
API_VERSION = "v1"

# If applicable, you'd add these environment variables through Railway's web interface
# DATABASE_URL = ""
# SUPABASE_URL = ""
# SUPABASE_KEY = ""
